services:
  financial_analyst:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial_analyst
    ports:
      - "5002:5002"  # Web application now using 5002 consistently
      - "5433:5432"  # PostgreSQL - use 5433 on host to avoid conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=financial_analyst
      - BUILD_NUMBER=${BUILD_NUMBER:-1}
    restart: unless-stopped

volumes:
  postgres_data: 